server:
  baseUrl:
    $env: AGENT_URL
  port:
    $env: PORT
  # apiKey:
  #   $env: API_KEY
  schemaPath: /api
  apiName: Simonas Public
  apiVersion: 1.0.0
  apiBasePath:
    $env: AGENT_ENDPOINT
  apiDocsPath: /api-docs
  defaultDID:
    create: false
    messagingServiceEndpoint: /messaging
constants:
  secretKey:
    $env: SECRET_KEY
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: postgres
      url:
        $env: HEROKU_POSTGRESQL_RED_URL
      ssl:
        rejectUnauthorized: false
      synchronize: true
      logging: false
      entities:
        $require: "@veramo/data-store?t=object#Entities"

agent:
  $require: "@veramo/core#Agent"
  $args:
    - plugins:
        - $require: "@veramo/data-store#DataStore"
          $args:
            - $ref: /dbConnection
        - $require: "@veramo/data-store#DataStoreORM"
          $args:
            - $ref: /dbConnection
      authorizedMethods:
        - dataStoreORMGetIdentifiers
        - dataStoreORMGetIdentifiersCount
        - dataStoreORMGetMessages
        - dataStoreORMGetMessagesCount
        - dataStoreORMGetVerifiableCredentialsByClaims
        - dataStoreORMGetVerifiableCredentialsByClaimsCount
        - dataStoreORMGetVerifiableCredentials
        - dataStoreORMGetVerifiableCredentialsCount
        - dataStoreORMGetVerifiablePresentations
        - dataStoreORMGetVerifiablePresentationsCount
