server:
  baseUrl:
    $env: AGENT_URL
  port:
    $env: PORT
  # apiKey:
  #   $env: API_KEY
  schemaPath: /api
  apiName: Simonas Public
  apiVersion: 1.0.0
  apiBasePath:
    $env: AGENT_ENDPOINT
  apiDocsPath: /api-docs
  defaultDID:
    create: false
    messagingServiceEndpoint: /messaging
constants:
  secretKey:
    $env: SECRET_KEY
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: postgres
      url:
        $env: HEROKU_POSTGRESQL_RED_URL
      ssl:
        rejectUnauthorized: false
      synchronize: true
      logging: false
      entities:
        $require: "@veramo/data-store?t=object#Entities"

ethr-did-resolver:
  $require: ethr-did-resolver?t=function&p=/ethr#getResolver
  $args:
    - networks:
        - name: mainnet
          rpcUrl: https://mainnet.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
        - name: rinkeby
          rpcUrl: https://rinkeby.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
        - name: ropsten
          rpcUrl: https://ropsten.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
        - name: kovan
          rpcUrl: https://kovan.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
        - name: goerli
          rpcUrl: https://goerli.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
        - name: private
          rpcUrl: http://localhost:8545/
          registry: '0x05cc574b19a3c11308f761b3d7263bd8608bc532'

web-did-resolver:
  $require: web-did-resolver?t=function&p=/web#getResolver

universal-resolver:
  $require: '@veramo/did-resolver#UniversalResolver'
  $args:
    - url: https://dev.uniresolver.io/1.0/identifiers/

resolver:
  $require: did-resolver#Resolver
  $args:
    - ethr:
        $ref: /ethr-did-resolver
      web:
        $ref: /web-did-resolver
      io:
        $ref: /universal-resolver
      elem:
        $ref: /universal-resolver
      key:
        $ref: /universal-resolver
      ion:
        $ref: /universal-resolver
      sov:
        $ref: /universal-resolver


agent:
  $require: "@veramo/core#Agent"
  $args:
    - plugins:
        - $require: '@veramo/did-resolver#DIDResolverPlugin'
          $args:
            - resolver:
                $ref: /resolver
        - $require: "@veramo/data-store#DataStore"
          $args:
            - $ref: /dbConnection
        - $require: "@veramo/data-store#DataStoreORM"
          $args:
            - $ref: /dbConnection
      authorizedMethods:
        - resolveDid
        - dataStoreGetMessage
        - dataStoreGetVerifiableCredential
        - dataStoreGetVerifiablePresentation
        - dataStoreORMGetIdentifiers
        - dataStoreORMGetIdentifiersCount
        - dataStoreORMGetMessages
        - dataStoreORMGetMessagesCount
        - dataStoreORMGetVerifiableCredentialsByClaims
        - dataStoreORMGetVerifiableCredentialsByClaimsCount
        - dataStoreORMGetVerifiableCredentials
        - dataStoreORMGetVerifiableCredentialsCount
        - dataStoreORMGetVerifiablePresentations
        - dataStoreORMGetVerifiablePresentationsCount
